services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - ./docs:/app/docs # Documentation générée montée dans le conteneur
    environment:
      - FLASK_ENV=development

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docs:/app/docs # Documentation montée dans le conteneur NGINX
    depends_on:
      - app
