name: CI Pipeline

on:
  push:
    branches: [ main, qualif ]
  pull_request:
    branches: [ main, qualif ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run tests with pytest
        run: |
          pytest

      - name: Security check with bandit
        run: |
          bandit -r app

      - name: Generate documentation with pydoc
        run: |
          mkdir -p docs
          python -m pydoc -w app.main
          mv app.main.html docs/

      - name: Zip documentation
        run: |
          zip -r docs.zip docs

      - name: Build Docker image
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            IMAGE_TAG="latest"
          else
            IMAGE_TAG="qualif"
          fi
          echo "Build Docker image with tag: $IMAGE_TAG"
          docker build -t quentingrt/pipelines:$IMAGE_TAG .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            IMAGE_TAG="latest"
          else
            IMAGE_TAG="qualif"
          fi
          echo "Push Docker image with tag: $IMAGE_TAG"
          docker push quentingrt/pipelines:$IMAGE_TAG

      - name: Build additional artifact
        run: |
          mkdir -p build
          zip -r build/app_build.zip app

      # ----------------------------------------------------
      # Étapes pour créer la Release et y téléverser les assets
      # ----------------------------------------------------

      - name: Create GitHub Release
        id: create_release
        if: contains('main,qualif', github.ref_name)
        uses: actions/create-release@v1
        with:
          # On génère un tag unique basé sur la branche et le numéro de run
          tag_name: "v_${{ github.ref_name }}_${{ github.run_number }}"
          release_name: "Release branch ${{ github.ref_name }} (run #${{ github.run_number }})"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset (docs)
        if: contains('main,qualif', github.ref_name)
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./docs.zip
          asset_name: docs.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset (app_build)
        if: contains('main,qualif', github.ref_name)
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/app_build.zip
          asset_name: app_build.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
